name: CI

on:
  push:
    branches: [ "main", "MGCSS" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Make gradlew executable
        run: chmod +x P1/gradlew

      - name: Build project
        run: cd P1 && ./gradlew build

      - name: Run tests
        run: cd P1 && ./gradlew test
