name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x P1/gradlew

      - name: Build project
        run: cd P1 && ./gradlew build

      - name: Run tests
        run: cd P1 && ./gradlew test

      - name: Build Docker image
        run: docker build -t mgcss-track ./P1

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
